create database controle_estoque;
-- MySQL Script generated by MySQL Workbench
-- Sun Aug 25 11:34:23 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema controlestoque
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema controlestoque
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `controlestoque` DEFAULT CHARACTER SET utf8 ;
USE `controlestoque` ;

-- -----------------------------------------------------
-- Table `controlestoque`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controlestoque`.`usuario` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(75) NOT NULL,
  `Email` VARCHAR(75) NOT NULL,
  `Password` VARCHAR(75) NOT NULL,
  `Dataregistro` DATE NOT NULL,
  `Permissao` INT NOT NULL,
  PRIMARY KEY (`iduser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlestoque`.`Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controlestoque`.`Produto` (
  `CodRefiProduto` INT NOT NULL AUTO_INCREMENT,
  `Nomeproduto` VARCHAR(75) NOT NULL,
  `usuario_iduser` INT NOT NULL,
  PRIMARY KEY (`CodRefiProduto`),
  INDEX `fk_Produto_usuario_idx` (`usuario_iduser` ASC) VISIBLE,
  CONSTRAINT `fk_Produto_usuario`
    FOREIGN KEY (`usuario_iduser`)
    REFERENCES `controlestoque`.`usuario` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlestoque`.`Fabricante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controlestoque`.`Fabricante` (
  `idFabricante` INT NOT NULL AUTO_INCREMENT,
  `Nomefabricante` VARCHAR(75) NOT NULL,
  `CNPJFabricante` VARCHAR(75) NOT NULL,
  `EmailFabricante` VARCHAR(75) NOT NULL,
  `EnderecoFabricante` VARCHAR(75) NOT NULL,
  `TelefoneFabricante` VARCHAR(75) NOT NULL,
  `usuario_iduser` INT NOT NULL,
  PRIMARY KEY (`idFabricante`),
  INDEX `fk_Fabricante_usuario1_idx` (`usuario_iduser` ASC) VISIBLE,
  CONSTRAINT `fk_Fabricante_usuario1`
    FOREIGN KEY (`usuario_iduser`)
    REFERENCES `controlestoque`.`usuario` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlestoque`.`Representante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controlestoque`.`Representante` (
  `idRepresentante` INT NOT NULL AUTO_INCREMENT,
  `NomeRepresentante` VARCHAR(75) NOT NULL,
  `TelefoneRepresentante` VARCHAR(16) NOT NULL,
  `EmailRepresentante` VARCHAR(45) NOT NULL,
  `Fabricante_idFabricante` INT NOT NULL,
  `usuario_iduser` INT NOT NULL,
  PRIMARY KEY (`idRepresentante`),
  INDEX `fk_Representante_Fabricante1_idx` (`Fabricante_idFabricante` ASC) VISIBLE,
  INDEX `fk_Representante_usuario1_idx` (`usuario_iduser` ASC) VISIBLE,
  CONSTRAINT `fk_Representante_Fabricante1`
    FOREIGN KEY (`Fabricante_idFabricante`)
    REFERENCES `controlestoque`.`Fabricante` (`idFabricante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Representante_usuario1`
    FOREIGN KEY (`usuario_iduser`)
    REFERENCES `controlestoque`.`usuario` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlestoque`.`Itens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controlestoque`.`Itens` (
  `idItens` INT NOT NULL,
  `QuantItens` DECIMAL NOT NULL,
  `QuantItensVend` DECIMAL NOT NULL,
  `ValCompItens` DECIMAL NOT NULL,
  `ValVendItens` DECIMAL NOT NULL,
  `DataCompraItens` DATE NOT NULL,
  `DataVenci_Itens` DATE NULL,
  `Ativo` INT NOT NULL,
  `Produto_CodRefiProduto` INT NOT NULL,
  `Fabricante_idFabricante` INT NOT NULL,
  `usuario_iduser` INT NOT NULL,
  PRIMARY KEY (`idItens`),
  INDEX `fk_Itens_Produto1_idx` (`Produto_CodRefiProduto` ASC) VISIBLE,
  INDEX `fk_Itens_Fabricante1_idx` (`Fabricante_idFabricante` ASC) VISIBLE,
  INDEX `fk_Itens_usuario1_idx` (`usuario_iduser` ASC) VISIBLE,
  CONSTRAINT `fk_Itens_Produto1`
    FOREIGN KEY (`Produto_CodRefiProduto`)
    REFERENCES `controlestoque`.`Produto` (`CodRefiProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Itens_Fabricante1`
    FOREIGN KEY (`Fabricante_idFabricante`)
    REFERENCES `controlestoque`.`Fabricante` (`idFabricante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Itens_usuario1`
    FOREIGN KEY (`usuario_iduser`)
    REFERENCES `controlestoque`.`usuario` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
